package w5;

import java.util.HashMap;

public final class b {

    /* renamed from: a  reason: collision with root package name */
    public static final HashMap f8015a;

    /* renamed from: b  reason: collision with root package name */
    public static final HashMap f8016b;

    /* renamed from: c  reason: collision with root package name */
    public static final HashMap f8017c;

    static {
        HashMap hashMap = new HashMap();
        f8015a = hashMap;
        hashMap.put(d.f8027h, new f(0));
        hashMap.put(d.f8029i, new f(0.0f));
        hashMap.put(d.f8031j, new f(0));
        hashMap.put(d.f8033k, new f(0));
        hashMap.put(d.f8035l, new f("00"));
        hashMap.put(d.f8037m, new f(0));
        hashMap.put(d.f8039n, new f(0.0f));
        hashMap.put(d.f8041o, new f(0));
        hashMap.put(d.f8043p, new f("00"));
        hashMap.put(d.f8045q, new f(0.0f));
        hashMap.put(d.r, new f(0.0f));
        hashMap.put(d.f8048s, new f(0.0f));
        hashMap.put(d.f8049t, new f(0.0f));
        hashMap.put(d.f8051u, new f(0));
        hashMap.put(d.f8052v, new f("00"));
        hashMap.put(d.w, new f(0));
        hashMap.put(d.f8055x, new f("00"));
        hashMap.put(d.y, new f(0));
        hashMap.put(d.f8057z, new f("00"));
        hashMap.put(d.A, new f(0));
        hashMap.put(d.B, new f("00"));
        hashMap.put(d.C, new f(0.0f));
        hashMap.put(d.D, new f(0.0f));
        hashMap.put(d.E, new f(0));
        hashMap.put(d.F, new f("00"));
        hashMap.put(d.G, new f(0));
        hashMap.put(d.H, new f(0));
        hashMap.put(d.I, new f(0.0f));
        hashMap.put(d.J, new f(0.0f));
        hashMap.put(d.K, new f(0.0f));
        hashMap.put(d.L, new f(1));
        hashMap.put(d.M, new f("Sunday"));
        hashMap.put(d.N, new f("Sun"));
        hashMap.put(d.O, new f(0));
        hashMap.put(d.P, new f(0));
        hashMap.put(d.Q, new f("00"));
        hashMap.put(d.R, new f("January"));
        hashMap.put(d.S, new f("Jan"));
        hashMap.put(d.T, new f(0));
        hashMap.put(d.U, new f(0.0f));
        hashMap.put(d.V, new f(0));
        hashMap.put(d.W, new f("00"));
        hashMap.put(d.X, new f(1));
        hashMap.put(d.Y, new f(1));
        hashMap.put(d.Z, new f(false));
        hashMap.put(d.f8019a0, new f(false));
        hashMap.put(d.f8020b0, new f(""));
        hashMap.put(d.f8021c0, new f(""));
        hashMap.put(d.f8022d0, new f(""));
        hashMap.put(d.f8023e0, new f(""));
        hashMap.put(d.f8024f0, new f(0));
        hashMap.put(d.f8026g0, new f(0));
        hashMap.put(d.f8028h0, new f("AM"));
        hashMap.put(d.f8034k0, new f("en_US"));
        d dVar = d.f8040n0;
        hashMap.put(dVar, new f(0));
        d dVar2 = d.f8042o0;
        hashMap.put(dVar2, new f(false));
        d dVar3 = d.f8044p0;
        hashMap.put(dVar3, new f(0.0f));
        d dVar4 = d.f8046q0;
        hashMap.put(dVar4, new f(0.0f));
        hashMap.put(d.f8047r0, new f(false));
        d dVar5 = d.u0;
        hashMap.put(dVar5, new f(0));
        d dVar6 = d.f8053v0;
        hashMap.put(dVar6, new f(0));
        d dVar7 = d.f8054w0;
        hashMap.put(dVar7, new f(""));
        d dVar8 = d.f8058z0;
        hashMap.put(dVar8, new f(false));
        d dVar9 = d.A0;
        hashMap.put(dVar9, new f(0.0f));
        d dVar10 = d.B0;
        hashMap.put(dVar10, new f(0.0f));
        d dVar11 = d.C0;
        hashMap.put(dVar11, new f(0.0f));
        d dVar12 = d.D0;
        hashMap.put(dVar12, new f(0.0f));
        d dVar13 = d.E0;
        d dVar14 = dVar12;
        hashMap.put(dVar13, new f(0.0f));
        d dVar15 = d.F0;
        d dVar16 = dVar13;
        hashMap.put(dVar15, new f(0.0f));
        d dVar17 = d.G0;
        d dVar18 = dVar15;
        hashMap.put(dVar17, new f(0.0f));
        d dVar19 = d.K0;
        d dVar20 = dVar17;
        hashMap.put(dVar19, new f(0));
        d dVar21 = d.L0;
        d dVar22 = dVar19;
        hashMap.put(dVar21, new f(0));
        d dVar23 = d.M0;
        d dVar24 = dVar21;
        hashMap.put(dVar23, new f(0));
        d dVar25 = d.P0;
        d dVar26 = dVar23;
        hashMap.put(dVar25, new f(0));
        d dVar27 = d.Q0;
        hashMap.put(dVar27, new f("00"));
        d dVar28 = d.U0;
        d dVar29 = dVar27;
        hashMap.put(dVar28, new f(0));
        d dVar30 = d.X0;
        d dVar31 = dVar28;
        hashMap.put(dVar30, new f(1));
        HashMap hashMap2 = new HashMap();
        f8016b = hashMap2;
        hashMap2.put(dVar, new f(100));
        hashMap2.put(dVar2, new f(false));
        hashMap2.put(dVar3, new f(0.0f));
        hashMap2.put(dVar4, new f(0.0f));
        hashMap2.put(dVar5, new f(10));
        hashMap2.put(dVar6, new f(3));
        hashMap2.put(dVar7, new f("Waxing Gibbous"));
        hashMap2.put(dVar8, new f(true));
        hashMap2.put(dVar9, new f(0.0f));
        hashMap2.put(dVar10, new f(4.0f));
        hashMap2.put(dVar11, new f(9.8f));
        hashMap2.put(dVar14, new f(0.0f));
        hashMap2.put(dVar16, new f(36.0f));
        hashMap2.put(dVar18, new f(88.2f));
        hashMap2.put(dVar20, new f(36.0f));
        d dVar32 = dVar22;
        hashMap2.put(dVar32, new f(3457));
        d dVar33 = dVar24;
        hashMap2.put(dVar33, new f(34));
        hashMap2.put(dVar26, new f(10000));
        hashMap2.put(dVar25, new f(89));
        d dVar34 = dVar29;
        hashMap2.put(dVar34, new f("89"));
        hashMap2.put(dVar31, new f(0));
        hashMap2.put(dVar30, new f(1));
        HashMap hashMap3 = new HashMap();
        f8017c = hashMap3;
        hashMap3.put(dVar32, new f(0));
        hashMap3.put(dVar33, new f(0));
        hashMap3.put(dVar25, new f(0));
        hashMap3.put(dVar34, new f("00"));
    }
}
